### ISSUE TITLE
Reset implementation

### ISSUE THREAD

**Issue by langandrews** [langandrews/ps-game-jam2024#5]
Ability to rest the level back to start

**Comment by lmjustic** [comment]
Could probably just reload the scene entirely since its small enough. `SignalBus.LoadScene.emit(Global.game_data.get_current_level().scene)` or better yet add a new signal in SignalBus to reset level. `SignalBus.Reset.emit()` and have the level loader handle the `Global.game_data.get_current_level().scene`

More of the work will be from adding an indicator like a little wheel or bar that fills while holding "R" to reset the level (also ensure it empties and disappears)
